# Configuration du site BDE
title: "BDE - Bureau des Élèves"
description: "Site officiel du Bureau des Élèves - Événements et archives"
baseurl: "/bde" # Le sous-dossier de votre site GitHub Pages
url: "https://bde-esad-orleans.github.io" # Le domaine de base de votre site

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
permalink: pretty

# Collections pour les événements
collections:
  events:
    output: true
    permalink: /events/:name/
  archive:
    output: true
    permalink: /archive/:name/
  activites:
    output: true
    permalink: /activites/:name/
  association:
    output: true
    permalink: /association/:name/


# Configuration par défaut
defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "archive"
    values:
      layout: "event"

# Plugins (compatibles avec GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Configuration GitHub Pages
github: [metadata]

# Exclusions
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Inclusions pour les assets
include:
  - assets/
